name = "rrhhmod-backend"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
account_id = "d69bcb9a616ebb79cbda95fb21c8af53"

[[d1_databases]]
binding = "DB"
database_name = "db_mchk"
database_id = "29660806-f166-4150-b5f1-51d4a3aafe59"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "fc77679cb6c94ffbb09a750902e853cc"

[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
CORS_ORIGIN = "*"
JWT_SECRET = "rrhhmod-super-secret-key-change-in-production-2024"

# Build configuration
build = { command = "npm install && npm run build" }
